# Generated by Django 2.2.4 on 2020-01-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='username',
        ),
        migrations.RemoveField(
            model_name='replyenquiry',
            name='username',
        ),
    ]
