# Generated by Django 2.2.4 on 2020-01-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Years_of_Experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Category'),
        ),
    ]
