# Generated by Django 2.2.4 on 2019-10-21 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(9)])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')])),
            ],
        ),
    ]
