# Generated by Django 2.2.4 on 2020-01-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200109_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='receiver',
            new_name='user',
        ),
    ]
