# Generated by Django 2.2.4 on 2019-10-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_phoneotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
