# Generated by Django 2.2.4 on 2021-07-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210714_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
    ]
