# Generated by Django 2.2 on 2021-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210716_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital',
            new_name='username',
        ),
    ]
