# Generated by Django 2.2.4 on 2019-10-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20191021_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
