# Generated by Django 2.2.4 on 2020-01-11 20:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200111_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, ' HeartDisease'), (2, 'Cancer'), (3, 'Unintentional_injuries'), (4, 'Chronic_lower_respiratory'), (5, 'Stroke_cerebrovascular'), (6, 'Alzheimer'), (7, 'Diabetes'), (8, 'Influenza'), (9, 'Kidney'), (10, 'Suicide')], default=False, max_length=20, null=True),
        ),
    ]
