# Generated by Django 2.2.4 on 2019-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20191025_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
