# Generated by Django 2.2 on 2021-08-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210827_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='hospital',
        ),
    ]
