# Generated by Django 2.2.4 on 2020-01-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_user_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeartDisease', models.CharField(max_length=100, null=True)),
                ('Cancer', models.CharField(max_length=100, null=True)),
                ('Unintentional_injuries', models.CharField(max_length=100, null=True)),
                ('Chronic_lower_respiratory', models.CharField(max_length=100, null=True)),
                ('Stroke_cerebrovascular', models.CharField(max_length=100, null=True)),
                ('Alzheimer', models.CharField(max_length=100, null=True)),
                ('Diabetes', models.CharField(max_length=100, null=True)),
                ('Influenza', models.CharField(max_length=100, null=True)),
                ('Kidney', models.CharField(max_length=100, null=True)),
                ('Suicide', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(to='quickstart.Specialization'),
        ),
    ]
