# Generated by Django 2.2.4 on 2020-01-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_appointment_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
