# Generated by Django 2.2.4 on 2020-01-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20200112_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='specialist', to='quickstart.Specialization'),
        ),
    ]
