# Generated by Django 2.2 on 2021-08-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210827_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
    ]
