# Generated by Django 2.2.4 on 2019-10-22 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20191021_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='phone',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
