# Generated by Django 2.2.4 on 2019-10-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100, null=True)),
                ('Degree', models.CharField(max_length=100)),
                ('Years_of_Experience', models.IntegerField()),
                ('Specialization', models.CharField(choices=[('Cardio', 'Cardiologists'), ('Derma', 'Dermatalogist'), ('Immuno', 'Immunologists'), ('Endocrin', 'Endocrinologists'), ('Neuro', 'Neurologist'), ('Path', 'Pathologist'), ('Psych', 'Psychiatrists')], max_length=100)),
                ('Contact', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('image', models.ImageField(null='True', upload_to='pics')),
                ('Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Hospital_Name')),
            ],
        ),
    ]
