# Generated by Django 2.2.4 on 2020-01-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null='True', upload_to='pics'),
            preserve_default='True',
        ),
    ]
