# Generated by Django 2.2.4 on 2020-01-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20200112_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='Alzheimer',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Cancer',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Chronic_lower_respiratory',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Diabetes',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='HeartDisease',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Influenza',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Kidney',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Stroke_cerebrovascular',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Suicide',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Unintentional_injuries',
        ),
    ]
