# Generated by Django 2.2.4 on 2020-01-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20200113_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(related_name='specialist', to='quickstart.Specialization'),
        ),
    ]
