# Generated by Django 2.2.4 on 2019-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20191106_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Type_of_User',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
