# Generated by Django 2.2.4 on 2019-11-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_auto_20191107_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Years_of_Experience', models.IntegerField()),
                ('Specialization', models.CharField(choices=[('Cardio', 'Cardiologists'), ('Derma', 'Dermatalogist'), ('Immuno', 'Immunologists'), ('Endocrin', 'Endocrinologists'), ('Neuro', 'Neurologist'), ('Path', 'Pathologist'), ('Psych', 'Psychiatrists')], max_length=100)),
                ('Contact', models.IntegerField()),
                ('image', models.ImageField(null='True', upload_to='pics')),
                ('Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Hospital_Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Type_of_User',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null='True', upload_to='pics'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Doctor'),
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
