# Generated by Django 2.2.4 on 2019-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20191108_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='street_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Hospital_Name',
        ),
    ]
