# Generated by Django 2.2.4 on 2019-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20191108_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
