# Generated by Django 2.2.4 on 2019-11-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_doctor_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='hospital',
        ),
    ]
