# Generated by Django 2.2.4 on 2019-11-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_auto_20191111_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Full_Name',
            new_name='username',
        ),
    ]
