# Generated by Django 2.2.4 on 2019-11-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_replyenquiry_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
