# Generated by Django 2.2.4 on 2019-11-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
