# Generated by Django 2.2.4 on 2019-11-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_remove_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.CharField(max_length=100),
        ),
    ]
