# Generated by Django 2.2.4 on 2019-11-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_auto_20191115_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null='True', upload_to='pics'),
            preserve_default='True',
        ),
    ]
