# Generated by Django 2.2.4 on 2019-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_auto_20191116_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null='True', upload_to='pics'),
        ),
    ]
