# Generated by Django 2.2.4 on 2019-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0026_auto_20191116_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null='True', upload_to='pics'),
            preserve_default='True',
        ),
    ]
