# Generated by Django 2.2.4 on 2019-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0028_auto_20191117_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyenquiry',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
