# Generated by Django 2.2.4 on 2019-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0029_replyenquiry_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Problem',
            new_name='Query',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='age',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='replyenquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='replyenquiry',
            name='enquiry',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
