# Generated by Django 2.2.4 on 2019-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0030_auto_20191117_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='hospital_name',
            field=models.CharField(max_length=100),
        ),
    ]
