# Generated by Django 2.2.4 on 2019-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0032_auto_20191118_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='hospital_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
