# Generated by Django 2.2.4 on 2019-11-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0035_auto_20191118_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyenquiry',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
