# Generated by Django 2.2.4 on 2019-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20191022_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='Specialization',
            field=models.CharField(choices=[('Cardio', 'Cardiologists'), ('Derma', 'Dermatalogist'), ('Immuno', 'Immunologists'), ('Endocrin', 'Endocrinologists'), ('Neuro', 'Neurologist'), ('Path', 'Pathologist'), ('Psych', 'Psychiatrists')], max_length=100),
        ),
    ]
