# Generated by Django 2.2.4 on 2019-10-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20191022_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='Full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.DoctorProfile')),
            ],
        ),
    ]
