# Generated by Django 2.2.4 on 2019-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_phoneotp_sent_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=50)),
                ('Specialist', models.CharField(choices=[('Cardio', 'Cardiologists'), ('Derma', 'Dermatalogist'), ('Immuno', 'Immunologists'), ('Endocrin', 'Endocrinologists'), ('Neuro', 'Neurologist'), ('Path', 'Pathologist'), ('Psych', 'Psychiatrists')], max_length=100)),
                ('Problem', models.TextField(max_length=300)),
            ],
        ),
    ]
